version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: stsims-php8.1
    container_name: stsims-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
       - ./:/var/www
       - ./dockerize/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports: 
      - "9002:9000"
    networks:
      - dostnetwork

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: stsims-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "82:80"
    volumes:
      - ./:/var/www
      - ./dockerize/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - dostnetwork

#Docker Networks
networks:
  dostnetwork:
    external: true
volumes:
  dbdata:
    driver: local